services:
  postgres:
    image: bitnami/postgresql:16.3.0
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: pizzashop
    volumes:
      - pizzashop_db_data:/bitnami/postgresql
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  pizzashop_db_data:
